# Generated by Django 4.1 on 2022-09-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.IntegerField()),
                ('requestdatetime', models.DateTimeField()),
                ('smstext', models.CharField(max_length=200)),
            ],
        ),
    ]
